const mkuc mouse_chord_0[] PROGMEM = {{0, MOUSE_BUTTON_LEFT}};
const mkuc mouse_chord_1[] PROGMEM = {{0, MOUSE_BUTTON_LEFT|MOUSE_TOGGLE}};
const mkuc mouse_chord_2[] PROGMEM = {{0, MOUSE_BUTTON_LEFT|MOUSE_DOUBLE}};
const mkuc mouse_chord_3[] PROGMEM = {{0, MOUSE_BUTTON_MIDDLE}};
const mkuc mouse_chord_7[] PROGMEM = {{0, MOUSE_BUTTON_MIDDLE|MOUSE_TOGGLE}};
const mkuc mouse_chord_11[] PROGMEM = {{0, MOUSE_BUTTON_MIDDLE|MOUSE_DOUBLE}};
const mkuc mouse_chord_15[] PROGMEM = {{0, MOUSE_BUTTON_RIGHT}};
const mkuc mouse_chord_31[] PROGMEM = {{0, MOUSE_BUTTON_RIGHT|MOUSE_TOGGLE}};
const mkuc mouse_chord_47[] PROGMEM = {{0, MOUSE_BUTTON_RIGHT|MOUSE_DOUBLE}};
const chord_codes mouse_chord_map[64] PROGMEM =
{
    {1, mouse_chord_0},
    {1, mouse_chord_1},
    {1, mouse_chord_2},
    {1, mouse_chord_3},
    {0, 0},
    {0, 0},
    {0, 0},
    {1, mouse_chord_7},
    {0, 0},
    {0, 0},
    {0, 0},
    {1, mouse_chord_11},
    {0, 0},
    {0, 0},
    {0, 0},
    {1, mouse_chord_15},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {1, mouse_chord_31},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {1, mouse_chord_47},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
    {0, 0},
};
